# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben's Blog
email: spawpaw@hotmail.com
# description: > # this means to ignore newlines until "baseurl:"
#   site description
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spawpaw.github.io" # the base hostname & protocol for your site

default_username: Ben
# twitter_username: spawpaw
github_username:  spawpaw
# github's user id,auto get avatar by this id from github. see it at `https://api.github.com/users/{github_username}`
github_user_id: 18007922
# Build settings
markdown: kramdown



date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# default
#   - page
#   - post
theme: jekyll-theme-minimal